[toolchain]
anchor_version = "0.32.1"
solana_version = "4.2.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
attacker = "9ZCmUGqkrtBrm83uiiMwBgRrV2cBPE9HGMgA25iRJGkQ"
issuer_forge = "DLkwvpN7EjtXLiXJFMiibLf7NXgFFFTBCmMcFvKgsGe5"

[programs.localnet]
attacker = "Att4ckerRe1ay111111111111111111111111111111"
issuer_forge = "ForgePo1icy11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm --filter @forge/chain test"
