// The Drizzle schema. **On-chain remains the source of truth** — these tables
// exist so that the console shows state without an RPC call per row, and so
// that the journal has somewhere to live between events (docs/PLAN.md → "Data
// model").
//
// Two rules follow, and they apply to every table below:
//
// 1. **Every table carries `issuer_id`** — the same base58 key that is the
//    seed `["issuer", issuer_id]`. There is no translation between the
//    database and the chain anywhere, so there is no place where it could
//    land on the wrong issuer. Tenant isolation rests on it too (FR-036): the
//    RLS policies in T051 are written over one column, with no join at all.
// 2. **RLS is enabled here already, with no policies.** That is deny for
//    everyone except the table owner and the `service_role` the api uses. The
//    state "the table exists in Supabase but is not yet protected" never
//    exists — T051 adds policies to tables that are already closed, rather
//    than closing open ones.
//
// The `source_slot` and `synced_at` columns are the age of the mirror, not
// decoration: a row without them has not yet been seen on the network, and an
// old `synced_at` means the screen shows yesterday's membership. The program
// checks the powers anyway, but a screen that silently lies about roles is
// worse than an empty one in a compliance product.
import { sql } from 'drizzle-orm'
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  smallint,
  text,
  timestamp,
  unique,
  uniqueIndex,
} from 'drizzle-orm/pg-core'

/** The length of a base58 Solana address. A cheap check against an empty string. */
const BASE58_LENGTH = sql`between 32 and 44`

/**
 * `pending` — the issuance transaction is assembled, no confirmation from the
 * network yet. `live` — the mint exists. `paused` — a mirror of the
 * `Pausable` extension (FR-016); the mint itself remains authoritative.
 */
export const tokenState = pgEnum('token_state', ['pending', 'live', 'paused'])

/**
 * `pending` — the account is queued for thawing (FR-008b2); `thawed` —
 * thawed; `frozen` — frozen by an officer (FR-014). A thawed account is not a
 * permission to transfer: the rules are checked on every one (FR-008b1).
 */
export const holderState = pgEnum('holder_state', ['pending', 'thawed', 'frozen'])

/** Whose status this row is (FR-008a). Provider attestations live in SAS. */
export const statusSource = pgEnum('status_source', ['issuer', 'provider'])

export const issuers = pgTable(
  'issuers',
  {
    /**
     * The issuer's on-chain identifier: base58 of the key `IssuerConfig` is
     * derived from. The row legitimately exists before the transaction —
     * `issuer_id` is generated by the client ahead of it, which is exactly why
     * `source_slot` is nullable.
     */
    issuerId: text('issuer_id').primaryKey(),
    /**
     * Nullable, because the row is written by the indexer from
     * `initialize_issuer`, and the chain carries neither a legal name nor a
     * jurisdiction. Both are filled in by the onboarding screen in its own
     * task; until then the console shows the issuer by its key, not by an
     * invented name that would read as a real one.
     */
    legalName: text('legal_name'),
    /** ISO 3166-1 alpha-2. */
    jurisdiction: text('jurisdiction'),
    /** Who founded it. Grants no powers — the membership lives in `role_assignments`. */
    founderWallet: text('founder_wallet').notNull(),
    quorumN: smallint('quorum_n').notNull(),
    operationalKey: text('operational_key'),
    delegationMask: smallint('delegation_mask').notNull().default(0),
    sourceSlot: bigint('source_slot', { mode: 'number' }),
    syncedAt: timestamp('synced_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check('issuers_issuer_id_is_base58', sql`char_length(${t.issuerId}) ${BASE58_LENGTH}`),
    check('issuers_founder_is_base58', sql`char_length(${t.founderWallet}) ${BASE58_LENGTH}`),
    check(
      'issuers_jurisdiction_is_alpha2',
      sql`${t.jurisdiction} is null or ${t.jurisdiction} ~ '^[A-Z]{2}$'`,
    ),
    // `MIN_QUORUM` from constants.rs. The program rejects a quorum of 1, so
    // there is no point in the database being able to store it (FR-019).
    check('issuers_quorum_at_least_two', sql`${t.quorumN} >= 2`),
    check('issuers_delegation_mask_known', sql`${t.delegationMask} between 0 and 7`),
  ],
).enableRLS()

/**
 * A mirror of `IssuerConfig.members` — exactly that array, by its indices.
 *
 * `member_index` is not decorative: the signature bitmap in `ActionProposal`
 * (T025) indexes the membership slots themselves, so without the index a
 * collected quorum has nothing to be tied to. Empty slots do not enter the
 * mirror: removing a member leaves the slot free rather than shifting the
 * rest.
 */
export const roleAssignments = pgTable(
  'role_assignments',
  {
    issuerId: text('issuer_id')
      .notNull()
      .references(() => issuers.issuerId, { onDelete: 'cascade' }),
    memberIndex: smallint('member_index').notNull(),
    wallet: text('wallet').notNull(),
    /** The role bitmask as on chain: admin 1, compliance 2, attestor 4, observer 8. */
    roles: smallint('roles').notNull(),
    sourceSlot: bigint('source_slot', { mode: 'number' }).notNull(),
    syncedAt: timestamp('synced_at', { withTimezone: true }).notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.issuerId, t.memberIndex] }),
    // The program rejects a duplicate address: one person would have two votes,
    // i.e. a 2-of-N quorum collected with a single signature.
    uniqueIndex('role_assignments_issuer_wallet_key').on(t.issuerId, t.wallet),
    // Console login goes from the wallet address to the issuer (FR-034a), not the other way.
    index('role_assignments_wallet_idx').on(t.wallet),
    check('role_assignments_wallet_is_base58', sql`char_length(${t.wallet}) ${BASE58_LENGTH}`),
    check('role_assignments_member_index_in_range', sql`${t.memberIndex} between 0 and 7`),
    check('role_assignments_roles_not_empty', sql`${t.roles} between 1 and 15`),
  ],
).enableRLS()

export const tokens = pgTable(
  'tokens',
  {
    mint: text('mint').primaryKey(),
    issuerId: text('issuer_id')
      .notNull()
      .references(() => issuers.issuerId, { onDelete: 'restrict' }),
    symbol: text('symbol').notNull(),
    name: text('name').notNull(),
    decimals: smallint('decimals').notNull(),
    policyVersion: integer('policy_version').notNull().default(0),
    state: tokenState('state').notNull().default('pending'),
    sourceSlot: bigint('source_slot', { mode: 'number' }),
    syncedAt: timestamp('synced_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // The target of the composite key from `holders`: without this constraint
    // the denormalised `issuer_id` there could be set to someone else's.
    unique('tokens_mint_issuer_key').on(t.mint, t.issuerId),
    index('tokens_issuer_idx').on(t.issuerId),
    check('tokens_mint_is_base58', sql`char_length(${t.mint}) ${BASE58_LENGTH}`),
    check('tokens_decimals_in_range', sql`${t.decimals} between 0 and 9`),
    check('tokens_policy_version_non_negative', sql`${t.policyVersion} >= 0`),
  ],
).enableRLS()

/**
 * The issuer's own status registry (FR-008a) and the thaw queue (FR-008b2).
 *
 * This holds **one of the two** status sources; the verification provider's
 * attestations live in SAS and are not mirrored into the database — the rule
 * merges them at the moment of transfer, and merges towards the stricter
 * (FR-008a1).
 */
export const holders = pgTable(
  'holders',
  {
    mint: text('mint').notNull(),
    wallet: text('wallet').notNull(),
    // The denormalisation is deliberate: RLS must cut a row off by one column,
    // with no join to `tokens`. The composite key below keeps it from
    // diverging from the truth.
    issuerId: text('issuer_id').notNull(),
    state: holderState('state').notNull().default('pending'),
    tier: smallint('tier'),
    /** ISO 3166-1 alpha-2, as for the issuer. */
    jurisdiction: text('jurisdiction'),
    statusSource: statusSource('status_source'),
    /** A denial from the issuer's own registry. Overrides any allow (FR-008a1). */
    denied: boolean('denied').notNull().default(false),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    thawedAt: timestamp('thawed_at', { withTimezone: true }),
    /** When the account joined the queue. The queue is `state = 'pending'`. */
    requestedAt: timestamp('requested_at', { withTimezone: true }).notNull().defaultNow(),
    sourceSlot: bigint('source_slot', { mode: 'number' }),
    syncedAt: timestamp('synced_at', { withTimezone: true }),
  },
  (t) => [
    primaryKey({ columns: [t.mint, t.wallet] }),
    foreignKey({
      columns: [t.mint, t.issuerId],
      foreignColumns: [tokens.mint, tokens.issuerId],
      name: 'holders_token_fk',
    }).onDelete('cascade'),
    // `GET /api/tokens/:mint/holders?state=pending` — the officer's queue.
    index('holders_queue_idx').on(t.issuerId, t.state),
    check('holders_wallet_is_base58', sql`char_length(${t.wallet}) ${BASE58_LENGTH}`),
    check('holders_tier_in_range', sql`${t.tier} is null or ${t.tier} between 0 and 255`),
    check(
      'holders_jurisdiction_is_alpha2',
      sql`${t.jurisdiction} is null or ${t.jurisdiction} ~ '^[A-Z]{2}$'`,
    ),
    // The queue is an account that has not been let in yet, and only it may
    // lack a thaw time. `frozen` does not restore that right: an officer
    // freezes an account already let in (FR-014), and the moment it was let in
    // stays in the journal rather than being erased by the action.
    check(
      'holders_thawed_at_matches_state',
      sql`(${t.state} = 'pending') = (${t.thawedAt} is null)`,
    ),
  ],
).enableRLS()

/**
 * The kinds of `events.kind`. A copy of the `kind` literals in
 * `@forge/shared/events`, and a copy on purpose: the database package does
 * not import the schemas (it would pull Zod into every script that only
 * wants a connection), and an enum in Postgres is what keeps a row with a
 * kind nobody reads from being written at all. `events.test.ts` in the
 * worker checks the two lists against each other.
 */
export const eventKind = pgEnum('event_kind', [
  'transfer',
  'refusal',
  'compliance',
  'attestation',
  'thaw',
  'holder_status',
])

/**
 * Everything the indexer pulls out of the logs (docs/PLAN.md → "Indexing"):
 * transfers, refusals, compliance actions, attestations, thaws and registry
 * changes. **One table, not the four in the plan's table list**: the feed
 * (FR-037), the journal export (FR-018) and the verifier (SC-006) all
 * consume one discriminated union, and four tables would make the journal a
 * union of four selects that must agree on ordering and paging by hand.
 *
 * The envelope is columns — it is what queries filter and order by. The
 * rest of the event is the `payload`, validated by the union schema before
 * it is written and again when it is read: the column set does not have to
 * change when a kind gains a field.
 *
 * The key is the pair `(signature, event_index)`, the same identity as
 * `eventKey` in `@forge/shared/events`: the indexer re-reads after a dropped
 * connection, and the second write of the same event must be a no-op.
 */
export const events = pgTable(
  'events',
  {
    signature: text('signature').notNull(),
    /** Ordinal of the event inside the transaction, from zero. */
    eventIndex: smallint('event_index').notNull(),
    kind: eventKind('kind').notNull(),
    issuerId: text('issuer_id').notNull(),
    mint: text('mint').notNull(),
    slot: bigint('slot', { mode: 'number' }).notNull(),
    /** Unix seconds; null where the node did not report it. */
    blockTime: bigint('block_time', { mode: 'number' }),
    /** The whole event as `@forge/shared/events` defines it, envelope included. */
    payload: jsonb('payload').notNull(),
    indexedAt: timestamp('indexed_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.signature, t.eventIndex] }),
    // The feed and the journal read one token in chain order; the export
    // adds a slot range on top of the same index.
    index('events_mint_slot_idx').on(t.mint, t.slot, t.eventIndex),
    index('events_issuer_slot_idx').on(t.issuerId, t.slot),
    check('events_signature_is_base58', sql`char_length(${t.signature}) between 64 and 88`),
    check('events_mint_is_base58', sql`char_length(${t.mint}) ${BASE58_LENGTH}`),
    check('events_slot_non_negative', sql`${t.slot} >= 0`),
  ],
).enableRLS()

/**
 * Where the indexer stopped: the last transaction applied, so that a
 * restart resumes from it instead of from the program's first slot.
 *
 * One row per program address. The only table without `issuer_id`: the
 * cursor belongs to the platform, not to a tenant, and there is no row of it
 * an issuer could be shown. RLS is on all the same — nobody but
 * `service_role` reads it.
 */
export const indexerState = pgTable('indexer_state', {
  programId: text('program_id').primaryKey(),
  lastSignature: text('last_signature').notNull(),
  lastSlot: bigint('last_slot', { mode: 'number' }).notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
}).enableRLS()

export type Issuer = typeof issuers.$inferSelect
export type NewIssuer = typeof issuers.$inferInsert
export type RoleAssignment = typeof roleAssignments.$inferSelect
export type NewRoleAssignment = typeof roleAssignments.$inferInsert
export type Token = typeof tokens.$inferSelect
export type NewToken = typeof tokens.$inferInsert
export type Holder = typeof holders.$inferSelect
export type NewHolder = typeof holders.$inferInsert
export type EventRow = typeof events.$inferSelect
export type NewEventRow = typeof events.$inferInsert
export type IndexerState = typeof indexerState.$inferSelect
