use anchor_lang::prelude::*;

use crate::constants::{ISSUER_SEED, MAX_MEMBERS, MIN_QUORUM};
use crate::error::ForgeError;
use crate::state::{delegation, role, IssuerConfig, Member};

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct InitializeIssuerArgs {
    /// The issuer's immutable identifier — the seed of its PDA. Generated by
    /// the client and signs nothing, so owning its key is not required.
    pub issuer_id: Pubkey,
    /// The initial membership: an address and a role mask. The order becomes
    /// the index in the `ActionProposal` signature bitmap, so it is stored as
    /// passed.
    pub members: Vec<Member>,
    pub quorum_n: u8,
    pub operational_key: Pubkey,
    pub delegation_mask: u8,
}

#[derive(Accounts)]
#[instruction(args: InitializeIssuerArgs)]
pub struct InitializeIssuer<'info> {
    #[account(
        init,
        payer = payer,
        space = 8 + IssuerConfig::INIT_SPACE,
        seeds = [ISSUER_SEED, args.issuer_id.as_ref()],
        bump,
    )]
    pub issuer_config: Account<'info, IssuerConfig>,

    /// Who pays the rent. Deliberately separated from `founder`: an
    /// officer's wallet created through Privy legitimately has zero SOL, and
    /// requiring it to pay would mean that login without crypto experience
    /// (FR-034) fails at the very first step. This signature grants no
    /// powers — no check below asks for it.
    #[account(mut)]
    pub payer: Signer<'info>,

    /// Who founds. Must be in the membership with the admin role: an issuer
    /// cannot be created on behalf of people you are not among.
    pub founder: Signer<'info>,

    pub system_program: Program<'info, System>,
}

pub(crate) fn handler(ctx: Context<InitializeIssuer>, args: InitializeIssuerArgs) -> Result<()> {
    let members = validate_members(&args.members)?;
    validate_quorum(args.quorum_n, &members)?;
    validate_delegation(args.delegation_mask, &args.operational_key)?;

    require!(
        members
            .iter()
            .any(|m| m.wallet == ctx.accounts.founder.key() && m.has(role::ADMIN)),
        ForgeError::NotAnAdmin
    );

    let config = &mut ctx.accounts.issuer_config;
    config.issuer_id = args.issuer_id;
    config.members = [Member::default(); MAX_MEMBERS];
    for (slot, member) in members.iter().enumerate() {
        config.members[slot] = *member;
    }
    config.member_slots = members.len() as u8;
    config.quorum_n = args.quorum_n;
    config.operational_key = args.operational_key;
    config.delegation_mask = args.delegation_mask;
    config.bump = ctx.bumps.issuer_config;

    Ok(())
}

fn validate_members(members: &[Member]) -> Result<&[Member]> {
    require!(members.len() >= MIN_QUORUM as usize, ForgeError::TooFewMembers);
    require!(members.len() <= MAX_MEMBERS, ForgeError::TooManyMembers);

    for (index, member) in members.iter().enumerate() {
        require!(member.roles != 0, ForgeError::MemberWithoutRole);
        require!(member.roles & !role::ALL == 0, ForgeError::UnknownRole);

        // FR-024: the attestor key can neither issue tokens, nor move funds,
        // nor change the policy. Here that becomes a check rather than a
        // promise: the attestor bit is incompatible with any other.
        if member.has(role::ATTESTOR) {
            require!(
                member.roles == role::ATTESTOR,
                ForgeError::AttestorHoldsOtherRoles
            );
        }

        // A duplicate address would give one person two votes in the quorum —
        // i.e. a 2-of-N quorum collected with a single signature.
        require!(
            !members[..index].iter().any(|m| m.wallet == member.wallet),
            ForgeError::DuplicateMember
        );
    }

    Ok(members)
}

fn validate_quorum(quorum_n: u8, members: &[Member]) -> Result<()> {
    require!(quorum_n >= MIN_QUORUM, ForgeError::QuorumTooSmall);

    let authorising = members
        .iter()
        .filter(|m| m.has(role::AUTHORISING))
        .count() as u8;

    // A threshold above the number of those who can sign at all would make
    // seizure and pause impossible forever — and that would surface on the
    // day the issuer received an order.
    require!(
        quorum_n <= authorising,
        ForgeError::QuorumExceedsSigners
    );

    Ok(())
}

fn validate_delegation(mask: u8, operational_key: &Pubkey) -> Result<()> {
    require!(
        *operational_key != Pubkey::default(),
        ForgeError::MissingOperationalKey
    );
    // FR-035a: issuance, seizure, pause and policy change are not in the mask
    // and cannot be. An unknown bit is an attempt to delegate something the
    // program cannot execute under the operational key, and it is rejected
    // here rather than silently stored until the first attempt to use it.
    require!(mask & !delegation::ALL == 0, ForgeError::UndelegatablePower);

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::VALIDATION_ERROR_BASE;

    fn member(seed: u8, roles: u8) -> Member {
        Member {
            wallet: Pubkey::new_from_array([seed; 32]),
            roles,
        }
    }

    fn two_admins() -> Vec<Member> {
        vec![member(1, role::ADMIN), member(2, role::ADMIN)]
    }

    fn err(result: Result<()>) -> u32 {
        match result.expect_err("expected a failure") {
            anchor_lang::error::Error::AnchorError(e) => e.error_code_number,
            other => panic!("unexpected error: {other:?}"),
        }
    }

    fn code(error: ForgeError) -> u32 {
        u32::from(error)
    }

    #[test]
    fn accepts_a_minimal_two_admin_issuer() {
        let members = two_admins();
        assert!(validate_members(&members).is_ok());
        assert!(validate_quorum(2, &members).is_ok());
    }

    #[test]
    fn rejects_a_single_member_issuer() {
        assert_eq!(
            err(validate_members(&[member(1, role::ADMIN)]).map(|_| ())),
            code(ForgeError::TooFewMembers)
        );
    }

    #[test]
    fn rejects_a_repeated_wallet() {
        // One address twice is a 2-of-N quorum collected with a single signature.
        let members = vec![member(1, role::ADMIN), member(1, role::COMPLIANCE)];
        assert_eq!(
            err(validate_members(&members).map(|_| ())),
            code(ForgeError::DuplicateMember)
        );
    }

    #[test]
    fn rejects_a_member_with_no_role_and_an_unknown_bit() {
        assert_eq!(
            err(validate_members(&[member(1, 0), member(2, role::ADMIN)]).map(|_| ())),
            code(ForgeError::MemberWithoutRole)
        );
        assert_eq!(
            err(validate_members(&[member(1, 1 << 6), member(2, role::ADMIN)]).map(|_| ())),
            code(ForgeError::UnknownRole)
        );
    }

    #[test]
    fn rejects_an_attestor_who_can_do_anything_else() {
        // FR-024: the attestor attests the reserve and can do nothing else.
        let members = vec![
            member(1, role::ADMIN),
            member(2, role::ADMIN),
            member(3, role::ATTESTOR | role::COMPLIANCE),
        ];
        assert_eq!(
            err(validate_members(&members).map(|_| ())),
            code(ForgeError::AttestorHoldsOtherRoles)
        );
    }

    #[test]
    fn accepts_an_attestor_who_can_do_nothing_else() {
        let members = vec![
            member(1, role::ADMIN),
            member(2, role::COMPLIANCE),
            member(3, role::ATTESTOR),
        ];
        assert!(validate_members(&members).is_ok());
    }

    #[test]
    fn rejects_a_quorum_of_one() {
        // FR-019 has no "one signature is enough" mode; SC-013 measures exactly that.
        assert_eq!(
            err(validate_quorum(1, &two_admins())),
            code(ForgeError::QuorumTooSmall)
        );
    }

    #[test]
    fn rejects_a_quorum_nobody_can_reach() {
        assert_eq!(
            err(validate_quorum(3, &two_admins())),
            code(ForgeError::QuorumExceedsSigners)
        );
    }

    #[test]
    fn does_not_count_observers_or_attestors_toward_the_quorum() {
        // An observer has no right to act, an attestor has no other powers — a
        // quorum of 3 is unreachable from such a membership, even though it
        // has four rows.
        let members = vec![
            member(1, role::ADMIN),
            member(2, role::COMPLIANCE),
            member(3, role::OBSERVER),
            member(4, role::ATTESTOR),
        ];
        assert!(validate_members(&members).is_ok());
        assert!(validate_quorum(2, &members).is_ok());
        assert_eq!(
            err(validate_quorum(3, &members)),
            code(ForgeError::QuorumExceedsSigners)
        );
    }

    #[test]
    fn refuses_to_delegate_a_power_that_moves_money() {
        // A bit outside `delegation::ALL` is an attempt to delegate issuance,
        // seizure, pause or policy change. There is nothing to express them
        // with, and that is the whole point.
        let key = Pubkey::new_from_array([9u8; 32]);
        assert_eq!(
            err(validate_delegation(1 << 3, &key)),
            code(ForgeError::UndelegatablePower)
        );
        assert_eq!(
            err(validate_delegation(delegation::ALL, &Pubkey::default())),
            code(ForgeError::MissingOperationalKey)
        );
        assert!(validate_delegation(delegation::ALL, &key).is_ok());
        assert!(validate_delegation(0, &key).is_ok());
    }

    #[test]
    fn error_numbering_leaves_the_refusal_range_untouched() {
        // 6000…6011 belong to the refusal codes (packages/shared/src/refusal.ts).
        // The checks start after them; the numbering layout itself is held by
        // `error.rs`, here only that this instruction does not intrude on it
        // is checked.
        assert_eq!(code(ForgeError::TooFewMembers), VALIDATION_ERROR_BASE);
        assert_eq!(code(ForgeError::MissingOperationalKey), VALIDATION_ERROR_BASE + 10);
    }
}
