#!/usr/bin/env node
// Carries the IDL from the Anchor build into git.
//
// `target/` is ignored, and `apps/web` and `apps/api` are built where neither
// WSL nor `anchor build` exists. Without a vendored copy the client exists only
// on the machine that just built the program.
//
// **Type and value come from one and the same text.** `target/types/issuer_forge.ts`
// is `export type IssuerForge = { … }`, and its body is already valid JSON, so
// the same block becomes both the type and the value. A camelCase copy made
// separately drifts from that type: Anchor 0.32.1 leaves `"path": "args.issuer_id"`
// in the type generator while `convertIdlToCamelCase` at runtime turns it into
// `args.issuerId`. Runtime is unaffected — `Program` converts whatever it is
// given — but two sources for one file would disagree for no reason.
//
//   node scripts/sync-idl.mjs          — overwrite the vendored copy
//   node scripts/sync-idl.mjs --check  — fail if the copy has drifted from the build
//
// `--check` silently skips when `target/` is absent: the gate has to be green
// on a machine without WSL and in a deployment where there is no on-chain
// build at all.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const IDL_JSON = join(root, 'target', 'idl', 'issuer_forge.json')
const IDL_TYPES = join(root, 'target', 'types', 'issuer_forge.ts')
const OUT = join(root, 'packages', 'chain', 'src', 'idl', 'issuer-forge.ts')

const HEADER = `// GENERATED by \`pnpm idl:sync\` from target/types. Do not edit by hand.
//
// The type is what \`anchor build\` generated; the value is the same text under
// an annotation of that type. The annotation is not decorative: it is the check
// that the vendored copy has not drifted from the program — an extra field or a
// different name will not compile.
//
// Names inside stay as Anchor writes them: \`Program\` runs the IDL it is given
// through its own camelCase conversion, so the spelling here does not affect
// runtime.
`

const checkOnly = process.argv.includes('--check')

function fail(message) {
  process.stderr.write(`sync-idl: ${message}\n`)
  process.exit(1)
}

function generate() {
  const declaration = readFileSync(IDL_TYPES, 'utf8').replace(/\r\n/g, '\n')
  const opening = declaration.indexOf('export type IssuerForge = ')
  if (opening === -1) fail(`${relative(root, IDL_TYPES)} does not declare the IssuerForge type`)

  const body = declaration.slice(opening + 'export type IssuerForge = '.length).trim().replace(/;$/, '')

  let parsed
  try {
    parsed = JSON.parse(body)
  } catch (error) {
    fail(`the type body is not JSON — Anchor changed its generator format: ${error.message}`)
  }

  // Two files from one build. A mismatch means `target/` is half-built, and
  // nothing can be vendored from it.
  const raw = JSON.parse(readFileSync(IDL_JSON, 'utf8'))
  if (parsed.address !== raw.address || parsed.instructions.length !== raw.instructions.length) {
    fail('target/idl and target/types disagree — rebuild the program')
  }

  return `${HEADER}\nexport type IssuerForge = ${body}\n\nexport const IDL: IssuerForge = ${body}\n`
}

if (!existsSync(IDL_JSON) || !existsSync(IDL_TYPES)) {
  if (checkOnly) {
    process.stdout.write('sync-idl: no target/ — nothing to compare against, skipping\n')
    process.exit(0)
  }
  fail(`no ${relative(root, IDL_JSON)} — build the program first (scripts/wsl-build.sh)`)
}

const generated = generate()

if (checkOnly) {
  if (!existsSync(OUT)) fail(`no ${relative(root, OUT)} — run \`pnpm idl:sync\``)
  const current = readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n')
  if (current !== generated) {
    fail(`${relative(root, OUT)} has drifted from the build — run \`pnpm idl:sync\``)
  }
  process.stdout.write('sync-idl: the vendored IDL matches the build\n')
  process.exit(0)
}

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, generated, 'utf8')
process.stdout.write(`sync-idl: wrote ${relative(root, OUT)}\n`)
